baseURL: 'https://anoopelias.github.io'
languageCode: en-us
title: Anoop's page
theme: PaperMod
params:
    ShowReadingTime: true
    homeInfoParams:
        Title: Anoop Elias
        Content: |
          Application Developer at /thoughtworks,\
          Lives in Bangalore, India \
          anoopelias@gmail.com
    socialIcons:
        - name: "Github"
          url: "https://github.com/anoopelias/"
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/anoopelias/"
        - name: "Stackoverflow"
          url: "https://stackoverflow.com/users/1328888/anoopelias"
        - name: "email"
          url: "mailto:anoopelias@gmail.com"
    assets:
        favicon: "/assets/favicon.ico"
        favicon16x16: "/assets/favicon-16x16.png"
        favicon32x32: "/assets/favicon-32x32.png"

menu:
    main:
        - identifier: side-projects
          name: My side projects
          url: /side-projects/side-projects
          weight: 10

